/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FlowRateListRelationFilter } from "../../flowRate/base/FlowRateListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { PulseLogListRelationFilter } from "../../pulseLog/base/PulseLogListRelationFilter";
import { VolumeListRelationFilter } from "../../volume/base/VolumeListRelationFilter";

@InputType()
class SensorWhereInput {
  @ApiProperty({
    required: false,
    type: () => FlowRateListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FlowRateListRelationFilter)
  @IsOptional()
  @Field(() => FlowRateListRelationFilter, {
    nullable: true,
  })
  flowRates?: FlowRateListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  pin?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PulseLogListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PulseLogListRelationFilter)
  @IsOptional()
  @Field(() => PulseLogListRelationFilter, {
    nullable: true,
  })
  pulseLogs?: PulseLogListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => VolumeListRelationFilter,
  })
  @ValidateNested()
  @Type(() => VolumeListRelationFilter)
  @IsOptional()
  @Field(() => VolumeListRelationFilter, {
    nullable: true,
  })
  volumes?: VolumeListRelationFilter;
}

export { SensorWhereInput as SensorWhereInput };
